CREATE TABLE IF NOT EXISTS USERS 
(
    UserID CHAR(26) PRIMARY KEY NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_DATE,
    Name VARCHAR(512) NOT NULL,
    Description TEXT DEFAULT NULL,
    DeviceID VARCHAR(64) DEFAULT NULL,
    AllowShareData BOOLEAN DEFAULT FALSE,
    Tags TEXT[] DEFAULT NULL,
    Images TEXT[] DEFAULT NULL,
    
    --Reputation
    Giver REAL DEFAULT 0,
    Taker REAL DEFAULT 0,

    --Contatct
    URL VARCHAR(512) NOT NULL,
    Email VARCHAR(512) DEFAULT NULL,
    Facebook VARCHAR(512) DEFAULT NULL,
    Instagram VARCHAR(512) DEFAULT NULL,
    Google VARCHAR(512) DEFAULT NULL,
    AdditionalData TEXT DEFAULT NULL,
    
    --Contact Address
    Address TEXT DEFAULT NULL,
    City VARCHAR(64) DEFAULT NULL,
    State VARCHAR(64) DEFAULT NULL,
    ZipCode INTEGER DEFAULT NULL,
    Country VARCHAR(64) DEFAULT NULL,

    Lat REAL DEFAULT NULL,
    Long REAL DEFAULT NULL 
);

CREATE SEQUENCE IF NOT EXISTS SEQ_PHONE_ID START 1;

CREATE TABLE IF NOT EXISTS PHONES
(
    PhoneID INTEGER DEFAULT NEXTVAL('SEQ_PHONE_ID'),    
    CreatedAt TIMESTAMP DEFAULT CURRENT_DATE,
    UserID CHAR(26) REFERENCES USERS(UserID),

    CountryCode VARCHAR(4) DEFAULT '+55',
    IsDefault BOOLEAN DEFAULT NULL,
    PhoneNumber VARCHAR(13) NOT NULL,
    Region CHAR(2) DEFAULT NULL,
    WhatsApp BOOLEAN DEFAULT NULL,

    PRIMARY KEY (PhoneID, UserID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    CreatedAt TIMESTAMP DEFAULT CURRENT_DATE,
    Name TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPOSALS
(
    ProposalID CHAR(26) PRIMARY KEY NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_DATE,
    LastUpdate TIMESTAMP DEFAULT CURRENT_DATE,
    UserID CHAR(26) REFERENCES USERS(UserID),

    Side VARCHAR(32) NOT NULL,
    ProposalType VARCHAR(32) NOT NULL,
    Tags TEXT[] DEFAULT NULL,
    Description TEXT NOT NULL,
    ProposalValidate TIMESTAMP DEFAULT NULL,
    Lat REAL DEFAULT NULL,
    Long REAL DEFAULT NULL,
    Range REAL DEFAULT NULL,
    AreaTags TEXT[] DEFAULT NULL,
    IsActive BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
    TransactionID CHAR(26) PRIMARY KEY NOT NULL,
    ProposalID CHAR(26) REFERENCES PROPOSALS(ProposalID),    
    GiverID CHAR(26) REFERENCES USERS(UserID),
    TakerID CHAR(26) REFERENCES USERS(UserID),
    CreatedAt TIMESTAMP DEFAULT CURRENT_DATE,

    GiverRating REAL DEFAULT 0,
    GiverReviewComment TEXT DEFAULT NULL,
    TakerRating REAL DEFAULT 0,
    TakerReviewComment TEXT DEFAULT NULL,
    Status VARCHAR(32) NOT NULL
);

