service:
  EnabledListeners:
    - https
  CleanupTimeout: 10s
  MaxHeaderSize: 1MiB
  SocketPath: /var/run/give-help.sock
  Host: 127.0.0.1
  Port: 80
  ListenLimit: 0
  KeepAlive: 3m
  ReadTimeout: 1m
  WriteTimeout: 30m
  TLSHost: 127.0.0.1
  TLSPort: 443
  TLSCertificate: etc/cert.crt
  TLSCertificateKey: etc/cert.key
  TLSListenLimit: 0
  TLSKeepAlive: 3m
  TLSReadTimeout: 1m
  TLSWriteTimeout: 30m

auth:
  Google:
    ClientID: xxx
    ClientSecret: yyyy
    Issuer: https://example.google
    Scopes:
      - openid
      - profile
      - email
  Facebook:
    ClientID: xxxx
    ClientSecret: yyyy
    Issuer: https://example.facebook
    Scopes:
      - openid
      - profile
      - email
  Token:
    PrivateKey: etc/key.pem
    PublicKey:  etc/public.pem
    ExpiresAt: 90m