version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8088
    
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
