---
swagger: "2.0"
info:
  title: give help
  version: 1.0.0
schemes:
  - https
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  APIKeyHeader:
    type: oauth2
    authorizationUrl: https://give-help
    tokenUrl: https://give-help
    flow: accessCode
    scopes:
      admin: "Admin scope"
      user: "Normal User scope"

security:
  - APIKeyHeader:
      - user

paths:
  "/auth/{provider}":
    get:
      tags:
        - auth
      summary: authorize user
      description: Get user authorization from providers
      operationId: redirectHandler
      security: []
      parameters:
        - $ref: "#/parameters/Provider"
      responses:
        "302":
          description: User get authorized
          schema:
            $ref: "#/definitions/LoggedUser"

  "/auth/{provider}/callback":
    get:
      tags:
        - auth
      summary: authorize user
      description: Get user authorization from providers
      operationId: callbackHandler
      security: []
      parameters:
        - $ref: "#/parameters/Provider"
      responses:
        "302":
          description: User get authorized
          schema:
            $ref: "#/definitions/LoggedUser"

parameters:
  Provider:
    name: provider
    in: path
    description: Provider to be used in Oauth
    required: true
    type: string
    enum:
      - google
      - facebook

definitions:
  LoggedUser:
    type: object
    required:
      - id
    properties:
      id:
        $ref: "#/definitions/ID"

  User:
    type: object
    required:
    properties:
      user_id:
        $ref: "#/definitions/ID"
      created_at:
        type: string
        format: date-time
      name:
        type: string
      description:
        type: string
      device_id:
        type: string
      location:
        $ref: "#/definitions/Location"
      contact:
        $ref: "#/definitions/Contact"
      allow_share_data:
        type: boolean
      images:
        type: array
        items:
          type: string
      reputation:
        $ref: "#/definitions/Reputation"
      tags:
        $ref: "#/definitions/Tags"

  Contact:
    type: object
    required:
    properties:
      phones:
        type: array
        items:
          $ref: "#/definitions/Phone"
      email:
        type: string
      instagram:
        type: string
      facebook:
        type: string
      google:
        type: string
      url:
        type: string
      additional_data:
        type: object
        additionalProperties:
          type: object

  Phone:
    type: object
    required:
    properties:
      region:
        type: string
      phone_number:
        type: string
      country_code:
        type: string
      whatsapp:
        type: boolean
      is_default:
        type: boolean

  Location:
    type: object
    required:
    properties:
      zip_code:
        type: integer
      address:
        type: string
      city:
        type: string
      state:
        type: string
      country:
        type: string
      lat:
        type: number
        format: float64
      long:
        type: number
        format: float64

  Reputation:
    type: object
    required:
    properties:
      giver:
        type: number
        format: float64
      taker:
        type: number
        format: float64

  Proposal:
    type: object
    required:
    properties:
      proposal_id:
        $ref: "#/definitions/ID"
      created_at:
        type: string
        format: date-time
      side:
        $ref: "#/definitions/Side"
      proposal_type:
        $ref: "#/definitions/Type"
      user_id:
        $ref: "#/definitions/ID"
      tags:
        $ref: "#/definitions/Tags"
      description:
        type: string
      proposal_validate:
        type: string
        format: date-time
      target_area:
        $ref: "#/definitions/Area"
      is_active:
        type: boolean

  Filter:
    type: object
    required:
    properties:
      tags:
        $ref: "#/definitions/Tags"
      target_area:
        $ref: "#/definitions/Area"
      side:
        $ref: "#/definitions/Side"        
      proposal_types:
        type: array
        items:
          $ref: "#/definitions/Type"
        x-omitempty: true
      description:
        type: string

  Transaction:
    type: object
    required:
    properties:
      transaction_id:
        $ref: "#/definitions/ID"    
      proposal_id:
        $ref: "#/definitions/ID"
      giver_id:
        $ref: "#/definitions/ID"
      taker_id:
        $ref: "#/definitions/ID"
      created_at:
        type: string
        format: date-time
      giver_review:
        $ref: "#/definitions/Review"
      taker_review:
        $ref: "#/definitions/Review"
      status:
        $ref: "#/definitions/TransactionStatus"

  Side:
    type: string
    enum:
      - offer
      - request
      - local-business

  Type:
    type: string
    enum:
      - job
      - service
      - product
      - finance

  Area:
    type: object
    required:
    properties:
      lat:
        type: number
        format: float64
      long:
        type: number
        format: float64
      range:
        type: number
        format: float64
      tags:
        $ref: "#/definitions/Tags"

  TransactionStatus:
    type: string
    enum:
      - open
      - in-progress
      - done
      - cancel

  Review:
    type: object
    required:
    properties:
      rating:
        type: integer
      comment:
        type: string

  Tags:
    type: array
    items:
      type: string
    x-omitempty: true 

  ID:
    type: string
    pattern: "^[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{26}$"
